### ISSUE TITLE
Question: Does this still work in 2019?

### ISSUE THREAD

**Issue by anshul-kai** [edgarsi/redis-module-shm#1]
No commits for 3 years. I'm wondering if this is still worthwhile using? Also, looks like it will not work on Mac.

PS. I haven't attempted to install this so pardon my ignorance.

**Comment by edgarsi** [comment]
Don't know. The module is rarely useful though. What's your use case?

**Comment by anshul-kai** [comment]
Thanks for checking in @edgarsi.

My use case has a very small data-set with about 100 keys all with roughly 25-50kb string values. I need an insanely high throughput with negligible latency to support 6700 reads and 3300 writes per second.

I've considered using Memcached but am a lot more familiar with Redis.

**Comment by edgarsi** [comment]
If you need to just support those ops, all you need is throughput, not latency. Pipelining should solve the issue. 

If you're rewriting values some 30 times each second, don't some of those changes get never seen by the readers? It's a bit strange, I'd like to know more about your project.

**Comment by anshul-kai** [comment]
Sure, I'm happy to share more details with you.

We are receiving 100 video streams at 30fps as base64Jpegs from another server. All of this data is being written to Redis over the local network. The receiving server has a 100 thread process which reads the data and then this data is passed onto another thread for compositing.

We can drop a frame or two but all the reading has to happen in less than 33ms before the next frame comes in which is why low latency is an issue.

Once consideration is that we run multiple redis instances (instead of read replicas) to overcome any bottlenecks. This will definitely solve our problem but just isn't graceful.

Do you know if Redis will hold up an operation while it's transmitting data over a tcp/unix socket?

**Comment by edgarsi** [comment]
Alright, first of all, since you're communicating through network, you won't be able to use the module, and need another solution. Luckily for you, there are several options.
As to your question, Redis server uses non-blocking io, so it won't hold up any operations. Redis client, however, does whatever you ask it to. You'll see in the options you have.

Will you need to scale? If not, you can make the sending server 100 threads each with a redis connection, fan out your SETs to those threads, and make the receiver server threads a connection each. Each connection can easily deal with with 30op/s, and, if the server can handle your aggressive polling, you've got a solution easily. Almost nothing changes in what I assume you've already have written.
The problem with this solution is the aggressive polling will abuse your server. As you wrote, your readers attempt 6700 ops with 25-50kb values. This is a lot of data to transfer, and every second poll you're reading the same frame. Can your server handle this? Will it handle more videos?

If the server is overloaded, or will be with more videos, you're better off with less redis connections and getting rid of the useless reads. To get rid of the connections, you will need to use pipelining, e.g. redisAppendCommand in hiredis. To get rid of the useless reads, don't use key-value store, use pubsubs. They are bound to have less overheads too.

I suggest you create 100 publish/subscribe channels. They're designed for your case perfectly. Call PUBLISH in a pipeline. Only read replies every once in a while, and you'll be practically nonblocking. The reader threads subscribe each to their channel, process frames without poll-induced delays.
https://redis.io/topics/pubsub

**Comment by anshul-kai** [comment]
Duh! When I first saw this lib, I thought it was a wrapper over an Redis installation but I'm realizing that this installs the binaries itself. So yes, I can't use it for over the network clients.

Thanks for the pub/sub suggestion, it is definitely more efficient than polling. 

To answer your questions, no, the use case is limited to 100 streams at the moment and so far in my testing of 50 streams, things have held up alright. There is some latency which would be nice to eliminate but it's acceptable.

Also, thanks for your insights on the non-blocking I/O nature of Redis although now that we're moving to a pub/sub model, I wonder if this is even a concern. In other words, should I be concerned about 200 subscribers clients receiving 50kb of data every 33ms? And if so, what would you recommend?

One solution is to split up the 100 streams over separate redis servers. Just feels a bit unnatural and maybe unnecessary. But as you may know, even 50ms of latency reduction is huge for my use case.

**Comment by edgarsi** [comment]
I see two possible concerns. One is the sender thread latency. The PUBLISH command is blocking, so you'll hit a msg per sec limit at a few thousand. That's why pipeling is still needed, or using multiple publisher threads.
Second, yes, you should be concerned about throughput. 200*50kb*33hz=300mb/s. That's well above 1gbit/s network capability, and even with a 10gbit/s network is something you should benchmark on your server - make sure the system can handle the load.
https://redis.io/topics/benchmarks

As for splitting things into multiple Redis servers, that's completely normal. CPUs have many cores and Redis is optimized to make most of just one. I agree that it's probably unnecessary.

**Comment by anshul-kai** [comment]
Thanks again @edgarsi. Did some load testing and I think we have a solution. Memcached couldn't hold up even with 24 threads and Redis outperformed it just as a single pub/sub server.

We've decided to go with multiple redis servers using the pub/sub model. We are running on 72-core servers all located on the same 10Gbps+ network.

Really appreciate your help.
